### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nagyanita** [nagyanita/szakdoga#1]
- [ ] szerkesztéshez még hozzá kell adni a mértékegység form-select-et
- [ ] maga a bevásárló listához még egy hozzáadás gomb, amivel "csak úgy" lehessen terméket hozzáadni
- [ ] szav.idő... Dávidtól megkérdezni, hogy a datepicker mennyire jó ide, illetve hogyan lehet használni?
- [ ] felhasználó kezelés... Ehhez kell a bejelentkezős akármi https://firebase.google.com/docs/auth/web/manage-users
- [ ] termékek képe: tooltip? Dávidtól ötletet kérni
